<style>
	<?php include_once dirname(__FILE__) . '/../resources/css/dotpay_payment_form.css'; ?>
</style>
<div class="dotpay_agreements_container">
    <label class="dotpay_agreements">
        <input type="checkbox" value="1" name="bylaw" required="true" checked="true" />
        <?php echo $this->getBylaw(); ?>
    </label>
	<label class="dotpay_agreements">
       * <?php echo $this->getPersonalData(); ?>
   </label>
</div>