<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>
	<?php include_once dirname(__FILE__) . '/../resources/css/dotpay_payment_form.css'; ?>
</style>
<div style="text-align: center;">
	<label style="margin: auto">
		<input name="blik_code" type="text" placeholder="<?php echo __('BLIK code', 'dotpay-payment-gateway'); ?>" pattern="[0-9]{6}" oninput="this.value = this.value.replace(/[^0-9]/g, ''); this.value = this.value.replace(/(\..*)\./g, '$1');" maxlength="6"/>
	</label>
</div>
	<?php if((bool)$this->isTestMode()) echo "<br><br><p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>notification_important</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."</p>"; ?>
<?php include(__DIR__.'/agreements.phtml'); ?>