<?php

if($this->getAmountForWidget() > 0) {$amountforchannelscc = $this->getAmountForWidget();}else{ $amountforchannelscc = '100.00';} 

if(!is_array($this->CheckChannelEnable(0,$amountforchannelscc)) || !in_array(self::$ccChannel,$this->CheckChannelEnable(0,$amountforchannelscc)))
{
	?>
	<script type = "text/javascript" >
		console.log('%c<?php echo "Credit Card (".self::$ccChannel."): channel is disabled for this order (id:".$this->get_option('id').", currency: ".$this->getCurrency().", amount: ".$this->getAmountForWidget()."). This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
		
		jQueryDotpayCodeCC = function(){
			if (typeof jQuery != 'undefined') {
				jQuery(document).ready(function () {
					jQuery('li.payment_method_Dotpay_cc').remove();					
				});
			};	
		};				
	
	</script>  
<?php

}else{
 $CheckCCEnabled = $this->CheckChannelDisable(self::$ccChannel);

 $getdatacc = $this->getDotpayChannels($amountforchannelscc);
 
 if(isset($CheckCCEnabled['is_disable']) && (string)$CheckCCEnabled['is_disable'] == 'true')
 {	
	$CCmessage = $CheckCCEnabled['disable_message'];
	 ?>
		<script type = "text/javascript" >
            console.log('%c<?php echo "Credit Card (".self::$ccChannel."): channel is disabled for this order, reason: ".$CCmessage." (id:".$this->get_option('id').", currency: ".$this->getCurrency().", amount: ".$this->getAmountForWidget()."). This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
			
			jQueryDotpayCodeCC = function(){
			    if (typeof jQuery != 'undefined') {
					jQuery(document).ready(function () {
						jQuery('li.payment_method_Dotpay_cc').remove();					
					});
				};	
			};				
		
		</script>  
<?php
 } else if (isset($getdatacc) && !empty($getdatacc) && (int)$CheckCCEnabled['id'] == "") {
?>
    <script type = "text/javascript">
    console.log('%c<?php echo "Credit Card (".self::$ccChannel."): channel not available for this order (id:".$this->get_option('id').", currency: ".$this->getCurrency().", amount: ".$this->getAmountForWidget()."). This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
    
    jQueryDotpayCodeCC = function(){
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function () {
                jQuery('li.payment_method_Dotpay_cc').remove();					
            });
        };	
    };				
</script>

<?php

 } else {

 ?>	 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<?php if((bool)$this->isTestMode()) echo "<br><p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>notification_important</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."</p>"; ?>
<?php include(__DIR__.'/agreements.phtml'); ?>

<script type = "text/javascript" >


// check agreements - bylaw

CheckBylawCC = function(){
		jQuery(document).ready(function(){
			
				if(jQuery('li.payment_method_Dotpay_cc > input#payment_method_Dotpay_cc:checked').length >0){
					jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_Dotpay_cc').change(function(){
					if(jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_Dotpay_cc').length < 1){
						console.log('%cSelect first PayPro S.A. Regulations of Payments !','background:red;color:#fff');
                        jQuery('li.payment_method_Dotpay_cc').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"});
						jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                        if(jQuery('div#payment div.form-row button#place_order').length > 0){
	                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                        }
					}else{
						console.log('Payment regulations accepted');
                        jQuery('li.payment_method_Dotpay_cc').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
						jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                        if(jQuery('div#payment div.form-row button#place_order').length > 0){
	                        jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                        }
					}
				});
				
			}


			});
    }



    jQueryEnableButtonCC = function(){
        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
        if(jQuery('div#payment div.form-row button#place_order').length > 0){
	        jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
        }
        jQuery('#dotpay_empty_channel').remove();
        jQuery('p.Nochannels').hide();
    };

    jQueryDotpayCodeCC = function(){
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function () {          
                if(jQuery('input#payment_method_Dotpay_cc').is(':checked')) { 
                    console.log('%cCredit Card method via Dotpay is checked','background: #cfcfcf; color: green;');
                    jQueryEnableButtonCC();
                    CheckBylawCC();
		        }
            });

            jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                    if (this.checked) {
                        if (this.value == 'Dotpay_cc') {                           
                            console.log('%cCredit Card method via Dotpay is checked manually','background: #cfcfcf; color: green;');
                            jQueryEnableButtonCC();
                            CheckBylawCC();
                        };
                    };
            });
        };
    };
 </script>   
 
<?php	 
 }
 }// check if exist channel to order
 ?>
<script type = "text/javascript" >
    if(window.jQuery){
        jQueryDotpayCodeCC();

    } else{   
        var script = document.createElement('script'); 
        document.head.appendChild(script);  
        script.type = 'text/javascript';
        script.src = "//ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js";

        script.onload = jQueryDotpayCodeCC;
    }
 </script>
<?php
        if (null == WC()->session->get('dotpay_payment_one_product_name')) {
			$this->setOneProductName($this->getProductName());
        }   
?>