<?php
 
if($this->getAmountForWidget() > 0) {$amountforchannelspaypo = $this->getAmountForWidget();}else{ $amountforchannelspaypo = '100.00';} 


if(!is_array($this->CheckChannelEnable(0,$amountforchannelspaypo,false,false)) || !in_array(self::$paypoChannel,$this->CheckChannelEnable(0,$amountforchannelspaypo,false,false))){    
	?>
	<script type = "text/javascript" >
		console.log('%c<?php echo "PayPo (".self::$paypoChannel."): channel is disabled for this order. This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
		
		jQueryDotpayCodePayPo = function(){
			if (typeof jQuery != 'undefined') {
				jQuery(document).ready(function () {
					jQuery('li.payment_method_Dotpay_paypo').remove();					
				});
			};	
		};				
	
	</script>  
<?php
}else{
 $CheckPayPoEnabled = $this->CheckChannelDisable(self::$paypoChannel);
 
 if(isset($CheckPayPoEnabled['is_disable']) && (string)$CheckPayPoEnabled['is_disable'] == 'true')
 {	
	$PayPomessage = $CheckPayPoEnabled['disable_message'];
	 ?>
		<script type = "text/javascript" >
            console.log('%c<?php echo "PayPo (".self::$paypoChannel."): channel is disabled for this order: ".$PayPomessage.". This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
			
			jQueryDotpayCodePayPo = function(){
			    if (typeof jQuery != 'undefined') {
					jQuery(document).ready(function () {
						jQuery('li.payment_method_Dotpay_paypo').remove();					
					});
				};	
			};				
		
		</script>  
<?php

} else if (null !== WC()->session->get('dotpay_payment_channels_cache_'.$this->getAmountForWidget().'_'.$this->getCurrency().'_'.$this->get_option('id')) && !empty(WC()->session->get('dotpay_payment_channels_cache_'.$this->getAmountForWidget().'_'.$this->getCurrency().'_'.$this->get_option('id')) && (int)$CheckPayPoEnabled['id'] == "")) {
?>
    <script type = "text/javascript">
    console.log('%c<?php echo "PayPo (".self::$paypoChannel."): channel not available for this order. This method has been blocked."; ?>', 'background: #cfcfcf; color: brown;');
    
    jQueryDotpayCodePayPo = function(){
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function () {
                jQuery('li.payment_method_Dotpay_paypo').remove();					
            });
        };	
    };				
</script>

<?php

 } else {

 ?>	 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<?php if((bool)$this->isTestMode()) echo "<br><p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>notification_important</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."</p>"; ?>
<?php include(__DIR__.'/agreements.phtml'); ?>

<script type = "text/javascript" >

    jQueryEnableButtonPayPo = function(){
        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
        jQuery('#dotpay_empty_channel').remove();
        jQuery('p.Nochannels').hide();
    };

    jQueryDotpayCodePayPo = function(){
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function () { 
                var CartAmountTotal = <?php echo $this->getAmountForWidget() ; ?>;
                if (CartAmountTotal < 40 || CartAmountTotal > 2000) {
                    console.log('%cPayPo channel: disabled -> wrong amount (not in range 40 - 2000): ' + CartAmountTotal,'background: #cfcfcf; color: brown;');
                    jQuery('li.payment_method_Dotpay_paypo').hide();
                }
                
                if(jQuery('input#payment_method_Dotpay_paypo').is(':checked')) { 
                    console.log('%cPayPo method via Dotpay is checked','background: #cfcfcf; color: green;');
                    jQueryEnableButtonPayPo();
		        }
            });

            jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                    if (this.checked) {
                        if (this.value == 'Dotpay_paypo') {                           
                            console.log('%cPayPo method via Dotpay is checked manually','background: #cfcfcf; color: green;');
                            jQueryEnableButtonPayPo();
                        };
                    };
            });
        };
    };
 </script>   
 
<?php	 
 }
}// check if exist channel to order
 ?>
<script type = "text/javascript" >
    if(window.jQuery){
        jQueryDotpayCodePayPo();

    } else{   
        var script = document.createElement('script'); 
        document.head.appendChild(script);  
        script.type = 'text/javascript';
        script.src = "//ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js";

        script.onload = jQueryDotpayCodePayPo;
    }
 </script> 
<?php
        if (null == WC()->session->get('dotpay_payment_one_product_name')) {
			$this->setOneProductName($this->getProductName());
        }   
?>