<?php if($this->isWidgetEnabled()): ?>
<style>
	<?php include_once dirname(__FILE__) . '/../resources/css/dotpay_payment_form.css'; ?>
</style>
<script type="text/javascript">
    var dotpayWidgetConfig = {
        sellerAccountId: <?php echo $this->getSellerId(); ?>,
        amount: '<?php echo $this->getAmountForWidget(); ?>',
        currency: '<?php echo $this->getCurrency(); ?>',
        lang: '<?php echo $this->getPaymentLang(); ?>',
        widgetFormContainerClass: 'my-form-widget-container',
        offlineChannel: 'mark',
        offlineChannelTooltip: true,
        disabledChannels: [<?php echo $this->getDisabledChannelsList(); ?>],
        host: '<?php echo $this->getPaymentChannelsUrl(); ?>'
    };
    if(jQuery != undefined) {
        setTimeout(function(){
            jQuery('.channel-container ').click(function(){
                jQuery('html, body').animate({
                    scrollTop: (jQuery('#place_order').offset().top) + 'px'
                }, 'fast');
            });
        }, 1500);
    }
</script>
<link href="<?php echo $this->getResourcePath(); ?>css/payment_widget.min.css" rel="stylesheet">
<script id="dotpay-payment-script" src="<?php echo $this->getResourcePath(); ?>js/payment_widget.js"></script>
<p class="my-form-widget-container"></p>
<?php endif; ?>
<?php if((bool)$this->isTestMode()) echo "<br><p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong>".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."</p>"; ?>
<?php include(__DIR__.'/agreements.phtml'); ?>
