<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script type="text/javascript">
jQueryDotpayChangeFont = function(){
             //change description style in payment method
   
             jQuery("label[for='payment_method_dotpay'], label[for*='payment_method_Dotpay']").html(function (i, h) {
                return h.replace(/\(([^\)]+)\)/, "<small>( $1 )</small>");
            });
}

//get additional params to 3DS v2

var dp_browser_javascriptenabled = "1";
    var dp_browser_javaenabled = window.navigator.javaEnabled();
    var dp_browser_language = window.navigator.language.slice(0,2);
    var dp_browser_screencolordepth = window.screen.colorDepth;
    var dp_browser_screenheight = window.screen.height;
    var dp_browser_screenwidth = window.screen.width;
    var dp_browser_timezone = new Date().getTimezoneOffset();



function createCookieDP(name, value, hours) {
  var expires;
  if (hours) {
    var date = new Date();
    date.setTime(date.getTime() + (hours * 60 * 60 * 1000));
    expires = "; expires=" + date.toGMTString();
  }
  else {
    expires = "";
  }
  document.cookie = escape(name) + "=" + escape(value) + expires + "; path=/;SameSite=Strict";
}


BrowserDetect3DSV2 = function(){
            jQuery(document).ready(function () {

                createCookieDP("dp_browser_javascriptenabled", dp_browser_javascriptenabled, "3");
                createCookieDP("dp_browser_javaenabled", dp_browser_javaenabled, "3");
                createCookieDP("dp_browser_language", dp_browser_language, "3");
                createCookieDP("dp_browser_screencolordepth", dp_browser_screencolordepth, "3");
                createCookieDP("dp_browser_screenheight", dp_browser_screenheight, "3");
                createCookieDP("dp_browser_screenwidth", dp_browser_screenwidth, "3");
                createCookieDP("dp_browser_timezone", dp_browser_timezone, "3");

            });
}


</script>
<?php

setcookie ("dp_channel_selected", "", time() - 3600);
unset($_COOKIE["dp_channel_selected"]);

// check if ID Dotpay is incorrect
if(!(bool)$this->isIDshopCorrectPattern()) {
         echo "<p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>sentiment_very_dissatisfied</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Incorrect module configuration! Invalid shop ID.', 'dotpay-payment-gateway')."<br></p>"; 
    if((bool)$this->isTestMode()) 
        {
        echo "<p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>notification_important</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."<br></p>"; 
        }

        ?>
        <script type="text/javascript">    
            jQueryDotpayWidget = function(){
                    if (typeof jQuery != 'undefined') {
                        jQuery(document).ready(function () {
                            jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                 if (this.checked) {
                                    if (this.value == 'dotpay') {
                                        jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', true);
                                            if(jQuery('div#payment div.form-row button#place_order').length > 0){
                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                            }
                                        }
                                    }
                            });

                            setTimeout(function(){
                                jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', true);
                                if(jQuery('div#payment div.form-row button#place_order').length > 0){
                                    jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                 }

                            }, 500);
                            console.log('%cIncorrect configuration Dotpay payment module! Invalid shop ID.This method has been blocked.','background: #f7e2e2; color: brown;');

                    });
                    BrowserDetect3DSV2(); 
                }
            };
        </script>
        <?php 

}else{

    // if ID Dotpay is correct

    if($this->getAmountForWidget() > 0) {$amountforchannels = $this->getAmountForWidget();}else{ $amountforchannels = '100.00';} 

    // if main method dotpay is enabled
    if ($this->isMainChannelEnabled() ) 
    {
        //if widget is enabled
            if ((bool)$this->isWidgetEnabled()) {
                ?>    

                <script type="text/javascript">
                        //check if browser supported apple pay
                    function isSupportedApplePay() {
                                return window.ApplePaySession && ApplePaySession.canMakePayments()
                            }
                        if (!isSupportedApplePay()) {
                            // APPLE PAY NOT SUPPORTED
                            var channel_apple = 262; //number of channel apple pay in Dotpay
                            console.log('%cYour browser NOT supported apple pay.','background: #cfcfcf; color: brown;'); 

                        } else {
                            var channel_apple = '';
                        }
                    
                </script>        

                <?php
                        //count all available channels for order /for specific amount and currency/
                        $disableforwidget = explode(',',$this->getDisabledChannelsList());
                        if(is_array($this->CheckChannelEnable(0,$amountforchannels,true))){ 
                            $channelsforwidget_real_el = array_diff($this->CheckChannelEnable(0,$amountforchannels), $disableforwidget);           
                            $channelsforwidget_real_count = count($channelsforwidget_real_el);
                            if($channelsforwidget_real_count >0 ){
                                $channelsforwidget_real = $channelsforwidget_real_el[key($channelsforwidget_real_el)];
                            }else{
                                $channelsforwidget_real = '';
                            }

                        } else { 
                            $channelsforwidget_real_el = array();
                            $channelsforwidget_real_count = 0;

                        }



                // if channels to widget > 0
                if ($channelsforwidget_real_count > 0 ) 
                {

                setcookie ("dp_channel_selected", "", time() - 3600);

                echo "<p style=\"font-size:1em;text-align:left;color:#2f2f97;padding:2px;border-radius:3px \" class=\"SelectChennelInfo\"><em>".__('Choose one of the payment channels below:', 'dotpay-payment-gateway')."</em></p>"; 
                ?>
                <p class="dotpay-form-widget-container"></p>
                <?php 
                    if((bool)$this->isTestMode()) 
                    {
                        echo "<p style=\"font-size:1.0em;text-align:center;background-color:#fff1f0;color:#d85030;border:1px solid rgba(216,80,48,0.3);padding:20px;border-radius:3px \"><strong><i class='material-icons'>notification_important</i> ".__('Attention!', 'dotpay-payment-gateway')."</strong> ".__('Test mode is activated. This is just a payment simulation.', 'dotpay-payment-gateway')."<br></p>"; 
                    }


                    include(__DIR__.'/agreements.phtml');

                ?>            
                <script type="text/javascript">

                    // check if: payment method is enabled + selected dotpay agreements + selected payment method (channel), then: activate payment button
                    PaymentButtonEnable = function(){

                      setTimeout(function(){
                            if(jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length >0 && jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length > 0 && jQuery('div.channel-container.dp_cloned').length > 0){

                                if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0  ) {
                                    
                                     //terms woocomerce accepted:
                                    if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
		                                   
                                        if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                    jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                   }
                                    }else{
                                          jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                    }

                                }

                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){                               

                                     //terms woocomerce accepted:
                                     if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
		                                   
                                           if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                         jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                      }
                                       }else{
                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                       }

                                }
                                            
                            }
                        }, 300);

                    }    

                // check agreements - bylaw

                    CheckBylawStandard = function(){
                        jQuery(document).ready(function(){
                            
                                if(jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length >0){

                                    jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').change(function(){
                                        if (jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length > 0) {

                                            console.log('Dotpay: Payment regulations accepted');
                                            jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({
                                                "background-color": "",
                                                "padding": "",
                                                "border-style": "",
                                                "border-width": "0px",
                                                "border-color": ""
                                            });

                                                    if( jQuery('div.channel-container.selected.dp_cloned').length > 0){ 
                                                            jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                            if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){
                                                                
                                                                //terms woocomerce accepted:
                                                                if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                    
                                                                    if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                    jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                }
                                                                }else{
                                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                }

                                                        }
                                                        }else{
                                                            jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                            if(jQuery('div#payment div.form-row button#place_order').length > 0){
                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                            }
                                                        }
                                            } else {
                                            console.log('%cDotpay: Select first PayPro S.A. Regulations of Payments!', 'background:red;color:#fff');
                                            jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({
                                                "background-color": "#ffeeed",
                                                "padding": "3px",
                                                "border-style": "solid",
                                                "border-width": "1px",
                                                "border-color": "#fd0c0c"
                                            });

                                            if (jQuery("button[name='woocommerce_checkout_place_order']").length > 0) {
                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                            } else if (jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                            }

                                            }

                                });
                                
                            }


                            });
                    }



                var dp_empty_channel = '<?php echo "<ul class=\"woocommerce-error\" role=\"alert\" id=\"dotpay_empty_channel\"><li data-id=\"dotpay_empty_channel\"><strong>". __('No payment channel selected!', 'dotpay-payment-gateway'). "</strong><br>". __('You must select one of the available payment channels to continue payment.', 'dotpay-payment-gateway'). "</li></ul>"; ?>';

                var dp_channels_choose_info = '<?php echo "<p style=\"font-size:1em;text-align:left;color:#2f2f97;padding:2px;border-radius:3px \" class=\"SelectChennelInfo\"><em>".__('Choose one of the payment channels below:', 'dotpay-payment-gateway')."</em></p>"; ?>';


                var dotpayWidgetConfig = {
                        sellerAccountId: '<?php echo $this->getSellerId(); ?>',
                        amount: '<?php echo $amountforchannels; ?>',
                        currency: '<?php echo $this->getCurrency(); ?>',
                        lang: '<?php echo $this->getPaymentLang(); ?>',
                        widgetFormContainerClass: 'dotpay-form-widget-container',
                        offlineChannel: 'mark',
                        offlineChannelTooltip: true,
                        channelNameVisibility: '<?php echo $this->getChannelNameVisiblity(); ?>',
                        disabledChannels: [<?php echo $this->getDisabledChannelsList(); ?>],
                        host: '<?php echo $this->getPaymentChannelsUrl(); ?>'
                    };

                    dotpayWidgetConfig.disabledChannels.push(channel_apple);

                    // when only 1 channel available, select it automatically
                    jQueryDotpayWidget1channel = function(){
                            // if (jQuery('div.dotpay-channels-selection > div.channel-container').length == 1) {
                                    setTimeout(function(){
                                                    createCookieDP("dp_channel_selected", "", "-1");
                                                    jQuery('div.dotpay-channels-selection > div.channel-container').trigger('click');
                                                    jQuery('.channels-wrapper').css('text-align','center');
                                                    if (jQuery('.channelSelectTXT').length < 1){
                                                        jQuery('<?php echo "<p style=\"font-size:1.2em;text-align:center;color:#3a3a3a;padding:20px; \"> <strong>".__('Selected', 'dotpay-payment-gateway') ; ?>: <span style=\"color:#881920;\">' + jQuery('div.channel-container.selected> div.image-container > img').attr("title") + '</span></strong></p>').insertBefore('div.channel-container.selected').addClass('channelSelectTXT');
                                                    }
                                                    jQuery('p.SelectChennelInfo').hide();
                                                // jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);

                                                if(jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length >0 && jQuery('div#payment div.form-row button#place_order').length > 0){
                                                    jQuery('input#dp_agreements_bylaw').prop( "checked", false );
                                                console.log('%cSelect first PayPro S.A. Regulations of Payments (2) !','background:red;color:#fff');
                                                
                                                jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"}); 

                                                        if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                        }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                        }
                                                }else{
                                                    jQuery('input#dp_agreements_bylaw').prop( "checked", false );
                                                    
                                                    if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                        }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                        
                                                                        //terms woocomerce accepted:
                                                                        if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                        }
                                                                        }else{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        }



                                                        }
                                                }


                                                jQuery(function($) {
                                                            $('input#dp_agreements_bylaw').change(function(){
                                                                if($(this).is(":checked")) {
                                                                    
                                                                        //terms woocomerce accepted:
                                                                        if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (3)');
                                                                                        }
                                                                        }else{
                                                                            jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                                        }


                                                                    console.log('Payment regulations accepted (3)');
                                                                    jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
                                                                } else {
                                                                    console.log('%cSelect first PayPro S.A. Regulations of Payments (3) !','background:red;color:#fff');
                                                                    jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"}); 

                                                                    if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                                        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                                    }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                                    }

                                                                }
                                                            });
                                                        });




                                                        if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0 && jQuery('input#dp_agreements_bylaw').is(":checked") == 'true'){
                                                            
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (4)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        }



                                                        }
                                                    
                                                        if(jQuery('div#payment div.form-row button#place_order').length > 0 && 
                                                            jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0 && 
                                                            jQuery('input#dp_agreements_bylaw').is(":checked") == 'true'){
                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);

                                                        }


                                                    jQuery('#dotpay_empty_channel').remove(); 
                                                    console.log('The only one available channel is selected (channel: '+jQuery('.dp_channel-input').attr("value")+')');
                                                    createCookieDP("dp_channel_selected", jQuery('.dp_channel-input').attr("value"), "0.08");
                                                    
                                                        
                                        }, 1000);
                        //	} 
                        };

                    jQueryDotpayWidgetSelectChannel = function(){
                                
                        if( jQuery('div.channel-container.selected.dp_cloned').length < 1){       
                            
                            if(jQuery("ul.wc_payment_methods input[type=radio]:checked").val() == 'dotpay') {

                            console.log('loaded main Dotpay payment method: waiting for payment channel selection...');
                            createCookieDP("dp_channel_selected", "", "-1");

                               if(jQuery('input#dp_agreements_bylaw').is(":checked")){
                                     console.log('Payment regulations accepted (4)');
                                     jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
                                }else{
                                    console.log('%cSelect first PayPro S.A. Regulations of Payments (4) !','background:red;color:#fff');
                                    //jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"});
                                    }


                                if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                    jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                    if(jQuery('ul#dotpay_empty_channel').length < 1 ) {
                                        jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                    }

                                }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                    jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                    if(jQuery('ul#dotpay_empty_channel').length < 1 ) {
                                        jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                    }

                                }

                            }


                            jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                if (this.checked) {
                                            if (this.value == 'dotpay') {                           
                                                console.log('%cDotpay main method is checked manually.','background: #cfcfcf; color: green;'); 
                                                console.log('loaded main Dotpay payment method: waiting for payment channel selection...1');               
                                                    if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0 ) {
                                                        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                        console.log('%cSelect first PayPro S.A. Regulations of Payments !','background:red;color:#fff');
                                                        jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"});
                                                        if(jQuery('ul#dotpay_empty_channel').length < 1 && jQuery('div.channel-container.selected.dp_cloned').length < 1) {
                                                            jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                                        }

                                                    }else if(jQuery('div#payment div.form-row button#place_order').length > 0 ) {
                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                        if(jQuery('ul#dotpay_empty_channel').length < 1 && jQuery('div.channel-container.selected.dp_cloned').length < 1) {
                                                            jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                                        }

                                                    }

                                                    PaymentButtonEnable();

                                                }  
                                                
                                                jQuery(function ($) {
                                                    $('input#dp_agreements_bylaw').parents('li.payment_method_dotpay').change(function () {    
                                                        if ($("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length > 0 && jQuery('div.channel-container.selected.dp_cloned').length > 0) {
                                                            
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (5)');
                                                                                        }
                                                                        }else{
                                                                            jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                                        }


                                                            console.log('Payment regulations accepted (5)');
                                                            jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({
                                                                "background-color": "",
                                                                "padding": "",
                                                                "border-style": "",
                                                                "border-width": "0px",
                                                                "border-color": ""
                                                            });
                                                        } else {
                                                            console.log('%cSelect first PayPro S.A. Regulations of Payments!', 'background:red;color:#fff');
                                                            jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({
                                                                "background-color": "#ffeeed",
                                                                "padding": "3px",
                                                                "border-style": "solid",
                                                                "border-width": "1px",
                                                                "border-color": "#fd0c0c"
                                                            });

                                                            if (jQuery("button[name='woocommerce_checkout_place_order']").length > 0) {
                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                            } else if (jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                            }

                                                        }
                                                    });
                                                });




                                            }
                        }); 		

                        }  

                        if(jQuery("ul.wc_payment_methods input[type=radio]:checked").val() == 'dotpay'){
                            console.log('%cDotpay main method is checked.','background: #cfcfcf; color: green;');  
                        }


                        setTimeout(function(){
                                                jQuery('input#dp_agreements_bylaw').parents('li.payment_method_dotpay').change(function () { 

                                                        if (jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length > 0 ) {
                                                                console.log('Payment regulations accepted (6)');
                                                                jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({
                                                                    "background-color": "",
                                                                    "padding": "",
                                                                    "border-style": "",
                                                                    "border-width": "0px",
                                                                    "border-color": ""
                                                                });
                                                            }else{
                                                                console.log('%cSelect first PayPro S.A. Regulations of Payments (6)!','background:#f783bb;color:#fff');

                                                                if (jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length < 1 && jQuery('div.channel-container.selected.dp_cloned').length < 1) {
                                                                    jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
                                                                 }else{
                                                                    jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"}); 
                                                                 }

                                                                    if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                                        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                                    }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                                    }

                                                            }

                                                            PaymentButtonEnable();  
                                                        
                                                });  

                                        }, 200);


                        setTimeout(function(){
                                            jQuery('.channel-container').on('click', function () {                             
                                                jQuery('.channels-wrapper').css('text-align','center');
                                                jQuery('.selected').clone().insertBefore('.dotpay-channels-selection').addClass('dp_cloned');
                                                jQuery('.dotpay-channels-selection').slideUp('600', 'swing');
                                                jQuery('<?php echo "<br><p style=\"font-size:1.2em;text-align:center;color:#2f2f97;padding:20px;border-radius:3px \"> <strong>".__('To select different channel click the above icon again', 'dotpay-payment-gateway')."</strong></p>"; ?>').insertAfter('.dp_cloned').addClass('channelSelect');
                                                if (jQuery('.channelSelectTXT').length < 1){
                                                    jQuery('<?php echo "<p style=\"font-size:1.2em;text-align:center;color:#3a3a3a;padding:20px; \"> <strong>".__('Selected', 'dotpay-payment-gateway') ; ?>: <span style=\"color:#881920;\">' + jQuery('div.channel-container.selected.dp_cloned > div.image-container > img').attr("title") + '</span></strong></p>').insertBefore('.dp_cloned').addClass('channelSelectTXT');
                                                }
                                                jQuery('.channelSelect').not(':last').remove();
                                                jQuery('.channelSelectTXT').not(':last').remove();
                                                jQuery('.dp_cloned').not(':last').remove();
                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0 && jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length < 1){
                                                    
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (6)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        }

                                                }
                                                        

                                                console.log('%cselected: ' + jQuery('div.channel-container.selected.dp_cloned > div.image-container > img').attr("title"), 'background: #cfcfcf; color: blue;');
                                                jQuery('#dotpay_empty_channel').remove();

                                                if(jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length >0 && jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length < 1){
                                                    console.log('%cSelect first PayPro S.A. Regulations of Payments (7) !','background:red;color:#fff');

                                                    if (jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length < 1 && jQuery('div.channel-container.selected.dp_cloned').length > 0  ) {
                                                        jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"});
                                                    }else{
                                                        jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
                                                    }

                                                    jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', true);
                                                    if(jQuery('div#payment div.form-row button#place_order').length > 0 ){
                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                    }
                                                }

                                                CheckBylawStandard();

                                                createCookieDP("dp_channel_selected", jQuery('.dp_channel-input').attr("value"), "0.08");
                                                if (jQuery('p.SelectChennelInfo').length > 0) {
                                                        jQuery('p.SelectChennelInfo').hide();  
                                                }else{
                                                    createCookieDP("dp_channel_selected", "", "-1");
                                                }

                                            });
                                        }, 1200);




                        setTimeout(function() {
                                            jQuery('.dotpay-channels').on('click', '.dp_cloned', function(){
                                                jQuery('.dotpay-channels-selection').slideDown('600','swing');
                                                jQuery('.dp_cloned').toggle().remove();
                                                jQuery('.selected').removeClass('selected');
                                                jQuery('.channelSelect').remove();
                                                jQuery('.channelSelectTXT').remove();
                                                jQuery('html, body').animate({scrollTop: (jQuery('.payment_method_dotpay').offset().top -100)}, 'fast');
                                                jQuery('.channels-wrapper').css('text-align','left');
                                                if( jQuery('div.channel-container.selected.dp_cloned').length < 1){
                                                    console.log('... waiting for payment channel selection');
                                                    
                                                    if (jQuery("label.dotpay_agreements > input[name=bylaw]:checked").parents('li.payment_method_dotpay').length < 1 && jQuery('div.channel-container.selected.dp_cloned').length < 1) {
                                                    jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "", "padding": "", "border-style": "", "border-width": "0px", "border-color": ""});
                                                    }

                                                    createCookieDP("dp_channel_selected", "", "-1");
                                                    jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', true);
                                                    if(jQuery('div#payment div.form-row button#place_order').length > 0){
                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                    }

                                                    if (jQuery('div.dotpay-channels-selection > div.channel-container').length > 1) {
                                                        jQuery('p.SelectChennelInfo').show();
                                                        createCookieDP("dp_channel_selected", "", "-1"); 
                                                    }

                                                    if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                        if(jQuery('ul#dotpay_empty_channel').length < 1 ) {
                                                            jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                                            createCookieDP("dp_channel_selected", "", "-1");
                                                        }

                                                    }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                        if(jQuery('ul#dotpay_empty_channel').length < 1 ) {
                                                            jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);
                                                            createCookieDP("dp_channel_selected", "", "-1");
                                                        }

                                                    }

                                                }
                                            });
                                        }, 1200); 

                };

                </script>
                <link href="<?php echo $this->getResourcePath(); ?>css/payment_widget.min.css" rel="stylesheet">
                <script id="dotpay-payment-script" src="<?php echo $this->getResourcePath(); ?>js/payment_widget.js"></script>
                <style>
                    <?php include_once dirname(__FILE__) . '/../resources/css/dotpay_payment_form.css'; ?>
                </style>
                <div id="dp_additional_info"></div>

                <?php
                // if channels to widget  == 1
                if($channelsforwidget_real_count == 1) {
                ?>

                <script type="text/javascript">

                    jQueryDotpayWidget = function(){
                            if (typeof jQuery != 'undefined') {
                                jQuery(document).ready(function () {
                                    jQueryDotpayChangeFont();
                                    BrowserDetect3DSV2();

                                    if(channel_apple != "" && 262 == <?php echo (int)$channelsforwidget_real; ?>) {
                                        jQuery('li.payment_method_dotpay').hide();
                                        console.log('%cOnly Apple Pay is available, but your device does not support this payment method.This method has been blocked.','background: #cfcfcf; color: brown;');
                                    }else{ 
                                        console.log('Only one (<?php echo $channelsforwidget_real_count; ?>) channels is available on widget.');
                                        jQueryDotpayWidget1channel(); 
                                        jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                                if (this.checked) {
                                                    if (this.value == 'dotpay') {                           
                                                        console.log('%cDotpay main method is checked manually.','background: #cfcfcf; color: green;'); 
                                                        jQueryDotpayWidget1channel();
                                                        createCookieDP("dp_channel_selected", jQuery('.dp_channel-input').attr("value"), "0.08");
                                                    }else{
                                                    
                                                        jQuery('input#dp_agreements_bylaw').prop( "checked", false );
                                                    
                                                        if(jQuery( "button[name='woocommerce_checkout_place_order']" ).length > 0) {
                                                                jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                        }else if(jQuery('div#payment div.form-row button#place_order').length > 0) {
                                                                        jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                        }
                                                }          
                                                }
                                            });                     
                                    } 

                            });
                        }
                    };

                </script>

                <?php
                } else {
                    if($channelsforwidget_real_count == 2) {
                        ?>      
                        <script type="text/javascript">
                        
                            jQueryDotpayWidget = function(){
                                    if (typeof jQuery != 'undefined') {
                                        jQuery(document).ready(function () {
                                            jQueryDotpayChangeFont();
                                            BrowserDetect3DSV2();
                                            
                                            if(channel_apple != "" && 262 == <?php echo (int)$channelsforwidget_real; ?>) {
                                                //jQuery('li.payment_method_dotpay').hide();
                                                console.log('%cYour device does not support Apple Pay payment method.This method has been blocked.','background: #cfcfcf; color: brown;');
                                                console.log('Only one (<?php echo $channelsforwidget_real_count; ?>) channels is available on widget.');
                                                jQueryDotpayWidget1channel(); 
                                                jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                                        if (this.checked) {
                                                            if (this.value == 'dotpay') {                           
                                                                console.log('%cDotpay main method is checked manually.','background: #cfcfcf; color: green;'); 
                                                                jQueryDotpayWidget1channel();
                                                            } else{
                                                                console.log('Selected another payment method: ' + this.value);
                                                                jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', false);
                                                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){
                                                                    
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (7)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        }

                                                                    }
                                                                jQuery('#dotpay_empty_channel').remove(); 
                                                            }           
                                                        }
                                                    });
                                                
                                            }else {
                                                jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                                    
                                                        if (this.checked) {
                                                            if (this.value == 'dotpay') {   
                                                                if(jQuery('.dp_channel-input').length < 2){
                                                                    console.log('Only one (<?php echo $channelsforwidget_real_count; ?>) channels is available on widget.');
                                                                }else{
                                                                    console.log('Available channels: '+ jQuery('.dp_channel-input').length);
                                                                }

                                                                console.log('%cDotpay main method is checked manually.','background: #cfcfcf; color: green;'); 
                                                                
                                                                if (jQuery('div.dotpay-channels-selection > div.channel-container').length == 1) {
                                                                    jQueryDotpayWidget1channel();
                                                                }
                                                                jQueryDotpayWidgetSelectChannel();
                                                            } else{
                                                                console.log('Selected another payment method: ' + this.value);
                                                                jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', false);
                                                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){
                                                                    
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (8)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        } 
                                                                    
                                                                }
                                                                jQuery('#dotpay_empty_channel').remove(); 
                                                            }         
                                                        }
                                                    });
                                                    jQueryDotpayWidgetSelectChannel();   

                                            }
                                    });
                                }
                            };
                        
                        </script>
                        
                <?php                
                    //if channels to widget == 2
                    }else{

                ?>
                        <script type="text/javascript">
                                        jQueryDotpayWidget = function(){
                                            if (typeof jQuery != 'undefined') {
                                                jQuery(document).ready(function () {
                                                    jQueryDotpayChangeFont();
                                                    BrowserDetect3DSV2();

                                                    console.log('Available channels in widget: <?php echo $channelsforwidget_real_count; ?>');

                                                    if(jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length >0){

                                                        if( jQuery('div.channel-container.selected.dp_cloned').length < 1){ 

                                                            console.log('loaded main Dotpay payment method: waiting for payment channel selection...');
                                                            jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', true);
                                                            if(jQuery('div#payment div.form-row button#place_order').length > 0){
                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', true);
                                                            }

                                                            if (jQuery('#dotpay_empty_channel').length < 1){
                                                                jQuery( "button[name='woocommerce_checkout_place_order']" ).before(dp_empty_channel);

                                                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('#dotpay_empty_channel').length < 1){
                                                                    jQuery( 'div#payment div.form-row button#place_order' ).before(dp_empty_channel);
                                                                }
                                                            }

                                                            console.log('Regulations of Payments (8) not checked');
                                                            //jQuery('li.payment_method_dotpay').find("label#agreements_bylaw").css({"background-color": "#ffeeed", "padding": "3px", "border-style": "solid", "border-width": "1px", "border-color": "#fd0c0c"});

                                                        }

                                                        CheckBylawStandard();
                                                        
                                                    }
                                                    jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                                                        if (this.checked) {
                                                            if (this.value == 'dotpay') {                           
                                                                console.log('%cDotpay main method is checked manually.','background: #cfcfcf; color: green;'); 
                                                                if (jQuery('div.dotpay-channels-selection > div.channel-container').length == 1) {
                                                                    jQueryDotpayWidget1channel();
                                                                }
                                                                jQueryDotpayWidgetSelectChannel();
                                                            } else{
                                                                console.log('Selected another payment method: ' + this.value);
                                                                jQuery( "button[name='woocommerce_checkout_place_order']" ).prop('disabled', false);
                                                                if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){
                                                                
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (9)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        }                                                                 
                                                                }
                                                                jQuery('#dotpay_empty_channel').remove(); 
                                                                createCookieDP("dp_channel_selected", jQuery('.dp_channel-input').attr("value"), "0.08");
                                                            }         
                                                        }
                                                    });
                                                    jQueryDotpayWidgetSelectChannel();                            
                                                });
                                            }
                                        };
                        </script>

                <?php  
                        } 
                    } //more then 1 channel is available


                // if channels to widget > 0
                }else { 

                ?>
                <script type="text/javascript">

                jQueryDotpayWidget = function(){
                            if (typeof jQuery != 'undefined') {
                                jQuery(document).ready(function () {
                                    jQueryDotpayChangeFont();
                                    BrowserDetect3DSV2();               		
                                    if (jQuery('div.dotpay-channels-selection > div.channel-container').length < 1) {
                                        jQuery('li.payment_method_dotpay').remove();
                                        console.log('%cThere are no payment channels available for this widget. This method has been blocked.','background: #c3c3c3; color: brown;');
                                } 
                                });
                            } 
                        };
                </script>
                <?php  

                        

                } //if channels to widget < 1


                    } else {
                        echo "<p style=\"font-size:1em;text-align:center;color:#2f2f97;padding:20px;border-radius:3px \" class=\"NoWidget\"><strong>".__('You chose the fast and secure payments via Dotpay.', 'dotpay-payment-gateway')."<br>".__('Continue to choose your payment method on the Dotpay website.', 'dotpay-payment-gateway')."</strong><br><small>".__('Or choose a different payment method.', 'dotpay-payment-gateway')."</small></p>";
                        ?>
                        <script type="text/javascript">
                        

                        jQueryDotpayWidget = function(){
                                    if (typeof jQuery != 'undefined') {
                                        jQuery(document).ready(function () {
                                            jQueryDotpayChangeFont();
                                            BrowserDetect3DSV2(); 		
                                            if (jQuery('div.dotpay-channels-selection > div.channel-container').length == 0) {
                                                    jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
                                                    if(jQuery('div#payment div.form-row button#place_order').length > 0 && jQuery('li.payment_method_dotpay > input#payment_method_dotpay:checked').length > 0){
                                                    
                                                                      //terms woocomerce accepted:
                                                                      if( jQuery("p.form-row.validate-required  input[name=terms]").parents("div.woocommerce-terms-and-conditions-wrapper").length >0 ){
                                                                            
                                                                            if(jQuery("p.form-row.validate-required  input[name=terms]:checked").parents("div.woocommerce-terms-and-conditions-wrapper").length >0)	{
                                                                                jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                                console.log('woocomerce terms accepted (10)');
                                                                                        }
                                                                        }else{
                                                                            jQuery('div#payment div.form-row button#place_order').prop('disabled', false);
                                                                        } 

                                                }
                                            
                                                    console.log('%cChannel selection payment only on the Dotpay website after redirection.','background: #cfcfcf; color: brown;');
                                                    createCookieDP("dp_channel_selected", jQuery('.dp_channel-input').attr("value"), "0.08");
                                        } 
                                        });
                                    } 
                                };
                        </script>
                        <?php 


                    } //if widget is disabled

     //if main method dotpay is enabled end.                
    }else{
        // if main method dotpay is disabled

            ?>
            <script type = "text/javascript">
                console.log('%cThe main payment method dotpay is disabled. This method has been blocked. Choose the other method', 'background: #cfcfcf; color: brown;');
                
                jQueryDotpayWidget = function(){
                    if (typeof jQuery != 'undefined') {
                        jQuery(document).ready(function () {
                            jQueryDotpayChangeFont();
                            BrowserDetect3DSV2();
                            jQuery('li.payment_method_dotpay').remove();					
                        });
                    }	
                };				
            </script>
            <?php

        } // if main method dotpay is disabled end.

 } // if Dotpay ID is correct end.
 ?>

<script type = "text/javascript" >
    if(window.jQuery){
        jQueryDotpayWidget();

    } else{   
        var script = document.createElement('script'); 
        document.head.appendChild(script);  
        script.type = 'text/javascript';
        script.src = "//ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js";

        script.onload = jQueryDotpayWidget;
    }
 </script>
<?php
        if (null == WC()->session->get('dotpay_payment_one_product_name')) {
			$this->setOneProductName($this->getProductName());
        }   
?>