<?php 
	if((bool)$this->isTestMode()) { 
        echo "<p style=\"font-size:1.0em;text-align:center;background-color:#f0feff;color:#00637e;border:1px solid rgba(0, 105, 57, 0.3);padding:20px;border-radius:3px \"><strong> ".__('Choose one of the payment methods above.', 'dotpay-payment-gateway')."</strong><br></p> "; 
    }
?>

<script type = "text/javascript" >

    jQueryEnableButtonTC = function(){
        jQuery("button[name='woocommerce_checkout_place_order']").prop('disabled', false);
        jQuery('#dotpay_empty_channel').remove();
        jQuery('p.Nochannels').hide();
    };

    jQueryDotpayCodeTC = function(){
        if (typeof jQuery != 'undefined') {
            jQuery(document).ready(function () { 
					jQueryEnableButtonTC();         
                	jQuery('.payment_method_Dotpay_tc').remove();                   

            });

            jQuery("ul.wc_payment_methods input[type=radio]").on("change", function () {
                    if (this.checked) {
                        if (this.value == 'Dotpay_tc') {                           
                            console.log('%cTrafnsfer method via Przelewy24 (Dotpay) is checked','background: #cfcfcf; color: green;');
                            jQueryEnableButtonTC();
                        };
                    };
            });
        }else{
			console.log("\n -------------------------------------------------------------------------------------\n");  	
      		console.log("%cWarning!","color:red;font-family:system-ui;font-size:3rem;-webkit-text-stroke: 1px black;font-weight:bold;");
	  		console.log("\n%cLoad jQuery first in your template! Then Przelewy24 (Dotpay) plugin.", "background: red; color: yellow; font-size: 1.2rem");
	  		console.log("%cOtherwise the Przelewy24 (Dotpay) plugin may not work properly!", "color: red; font-size: 1rem;font-weight: bold;");
	  		console.log("\n -------------------------------------------------------------------------------------\n"); 
		}
    };

    
    if(window.jQuery){
        jQueryDotpayCodeTC();

    } else{   
        var script = document.createElement('script'); 
        document.head.appendChild(script);  
        script.type = 'text/javascript';
        script.src = "//ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js";

        script.onload = jQueryDotpayCodeTC;
    }
 </script> 
<?php
        if (null == WC()->session->get('dotpay_payment_one_product_name')) {
			$this->setOneProductName($this->getProductName());
        }   
?>