<?php 
	if((bool)$this->isTestMode()) echo "<p style=\"font-size:1.0em;text-align:center;background-color:#f0feff;color:#00637e;border:1px solid rgba(0, 105, 57, 0.3);padding:20px;border-radius:3px \"><strong> ".__('Choose one of the payment methods above.', 'dotpay-payment-gateway')."</strong><br></p>";
?>

<script type="text/javascript">
if (typeof jQuery != 'undefined') {
	  console.log("\n -------------------------------------------------------------------------------------\n");  	
      console.log("%cWarning!","color:red;font-family:system-ui;font-size:3rem;-webkit-text-stroke: 1px black;font-weight:bold;");
	  console.log("\n%cLoad jQuery first in your template! Then Dotpay plugin.", "background: red; color: yellow; font-size: 1.2rem");
	  console.log("%cOtherwise the Dotpay plugin may not work properly!", "color: red; font-size: 1rem;font-weight: bold;");
	  console.log("\n -------------------------------------------------------------------------------------\n"); 
}

jQuery(document).ready(function() { 
	  jQuery('.payment_method_Dotpay_tc').remove();
});
</script>
