<?php 
	if((bool)$this->isTestMode()) echo "<p style=\"font-size:1.0em;text-align:center;background-color:#f0feff;color:#00637e;border:1px solid rgba(0, 105, 57, 0.3);padding:20px;border-radius:3px \"><strong> ".__('Choose one of the payment methods above.', 'dotpay-payment-gateway')."</strong><br></p>";
?>

<script type="text/javascript">
jQuery(document).ready(function() { 
	  jQuery('.payment_method_Dotpay_tc').remove();
});
</script>
