<?php if($this->isWidgetEnabled()): ?>
<script type="text/javascript">
    var dotpayWidgetConfig = {
        sellerAccountId: <?php echo $this->getSellerId(); ?>,
        amount: '<?php echo $this->getAmountForWidget(); ?>',
        currency: '<?php echo $this->getCurrency(); ?>',
        lang: '<?php echo $this->getPaymentLang(); ?>',
        widgetFormContainerClass: 'my-form-widget-container',
        offlineChannel: 'mark',
        offlineChannelTooltip: true,
        disabledChannels: [<?php echo $this->getDisabledChannelsList(); ?>],
        host: '<?php echo $this->getPaymentChannelsUrl(); ?>'
    };
    if(jQuery != undefined) {
        setTimeout(function(){
            jQuery('.channel-container ').click(function(){
                jQuery('html, body').animate({
                    scrollTop: (jQuery('#place_order').offset().top) + 'px'
                }, 'fast');
            });
        }, 1500);
    }
</script>
<link href="<?php echo $this->getPaymentUrl(); ?>widget/payment_widget.min.css" rel="stylesheet">
<script id="dotpay-payment-script" src="<?php echo $this->getPaymentUrl(); ?>widget/payment_widget.js"></script>
<p class="my-form-widget-container"></p>
<?php endif; ?>
<?php include(__DIR__.'/agreements.phtml'); ?>
