<div class="<?php echo $this->getAdminPromptClass(); ?>" tyle="text-align:left;font-size:14px;font-weight:normal">
    <a href="http://www.dotpay.pl/" target="_blank" ><img src="<?php echo $this->getAdminSettingsLogo(); ?>" style= "margin-top: 20px;" alt="<?php echo __('Dotpay.pl website', 'dotpay-payment-gateway'); ?>" title="www.dotpay.pl" width="250px" border="0"></a>
        <p><?php echo __('In response to the market\'s needs Dotpay has been delivering innovative Internet payment services providing the widest e-commerce solution offer for years. The domain is money transfers between a buyer and a merchant within a complex service based on counselling and additional security. Within an offer of Internet payments Dotpay offers over 140 payment channels including: mobile payments, instalments, cash, e-wallets, transfers and credit card payments.', 'dotpay-payment-gateway'); ?></p>
        <p class="main"><strong><?php echo __('Getting started', 'dotpay-payment-gateway'); ?></strong></p>
	<p>
            <ol>
                <li><?php echo __('Thanks to Dotpay payment module the only activities needed for integration are: ID and PIN numbers and URLC confirmation configuration.', 'dotpay-payment-gateway'); ?></li>
                <li><?php echo __('ID and PIN can be found in Dotpay panel in Settings in the top bar. ID number is a 6-digit string after # in a "Shop" line.', 'dotpay-payment-gateway'); ?></li>
		<li><?php echo __('Only thing You have to do is log in to the Dotpay user panel and untick "Block external URLC" option in Settings -> Notifications -> Urlc configuration -> Edit.', 'dotpay-payment-gateway'); ?></li>
            </ol>
        </p>
        <br>
        <p><a href="https://ssl.dotpay.pl/s2/login/registration/?affilate_id=woocommerce" class="button button-primary" target="_blank" title="<?php echo __('Account registration in Dotpay', 'dotpay-payment-gateway'); ?>"><?php echo __('Account registration in Dotpay', 'dotpay-payment-gateway'); ?></a> &nbsp;&nbsp;&nbsp;<a href="http://www.dotpay.pl/" target="_blank" class="button"><?php echo __('Dotpay Home Page', 'dotpay-payment-gateway'); ?></a></p>

</div>
