<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
    <title>Redirect form to the Przelewy24 payment</title>
        <script type="text/javascript">
            setTimeout(function(){document.getElementsByClassName('dotpay-form')[0].submit();}, 10);
        </script>
    </head>
    <body>
        <?php echo  __('You\'re being redirected to the payment operator, please wait ...', 'dotpay-payment-gateway'); ?>
        <?php $formData = $this->getHiddenFields(); ?>
        <form method="POST" class="dotpay-form" action="<?php echo $this->getPaymentUrl(); ?>">
            <?php foreach($formData as $name => $value): ?>
            <input type="hidden" name="<?php echo (string)$name; ?>" value="<?php echo (string)$value; ?>" />
            <?php endforeach; ?>
        </form>
    </body>
</html>
