<?php if($data['mp'] || $data['blik'] || $data['widget']) : ?>
    $(document).ready(function() {
        $('form[form-target]').hide();
        
        $('body').on('click', 'input[name="strategy"]', function(){
            $('form[form-target]').hide();
            $('form[form-target] input[type="submit"]').hide();
            
            $(this).each(function(key, val){
                var checked = $(val).is(':checked');
                var target = $(val).attr('form-target');
                
                var data = {};
                
                if('mp' === target) {
                    data.type = target;
                    data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();
                    
                    if(data.channel) {
                        $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="CHK"]').val(result);
                            submitHideShow(target);
                        });
                    }
                } else if('blik' === target) {
                    data.type = target;
                    data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();
                    data.blik = $('form[form-target="' + target + '"] input[name="blik_code"]').val();
                    
                    if(data.channel && data.blik) {
                        $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="CHK"]').val(result);
                            submitHideShow(target);
                        });
                    }
                } else if('dotpay' === target) {
                    data.type = target;
                    
                    $('form[form-target="' + target + '"] input[name="channel"]').each(function(key, val){
                        var channel = $(val).is(':checked');
                        var online = !$(val).parent().parent().hasClass('not-online');
                        if(channel && online) {
                            data.channel = $(val).val();
                            return false;
                        }
                    });
                    
                    if(data.channel) {
                        $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="CHK"]').val(result);
                            submitHideShow(target);
                        });
                    }
                }
                
                if(checked) {
                   $('form[form-target="' + target + '"]').show();
                }
            });
        });
        
        $('body').on('input', 'input[name="blik_code"]', function(){
            $('form[form-target] input[type="submit"]').hide();
            
            var target = $(this).attr('form-target');
        
            var data = {
                type: target,
                channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
                blik: $(this).val()
            };
            
            if(data.channel && data.blik) {
                $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                    $('form[form-target="' + target + '"] input[name="CHK"]').val(result);
                    submitHideShow(target);
                });
            }
        });
        
        $('body').on('click', '.channel-container', function(){
            $('form[form-target] input[type="submit"]').hide();
            
            var target = 'dotpay';
            var data = {};
            data.type = target;
            
            $('input[name="channel"]', this).each(function(key, val){
                var channel = $(val).is(':checked');
                var online = !$(val).parent().parent().hasClass('not-online');
                
                if(channel && online) {
                    data.channel = $(val).val();
                    return false;
                }
            });
            
            if(data.channel) {
                $.post('<?php echo $data['signature_url']; ?>', data, function(result) {
                    $('form[form-target="' + target + '"] input[name="CHK"]').val(result);
                    submitHideShow(target);
                });
            }
        });
        
        $('body').on('click', 'form[form-target] input[type="submit"]', function(){
            var target = $(this).attr('form-target');
            runBlockUI();
            $('form[form-target="' + target + '"]').submit();
        });
        
        function submitHideShow(target) {
            var result = false;
            
            var checkBylaw = false;
            var checkPersonalData = false;
            
            if(target) {
                checkBylaw = $('form[form-target="' + target + '"] input[name="bylaw"]').is(':checked');
                checkPersonalData = $('form[form-target="' + target + '"] input[name="personal_data"]').is(':checked')
            }
            
            if('mp' === target && checkBylaw && checkPersonalData) {
                $('form[form-target="' + target + '"] input[type="submit"]').show();
                result = true;
            } else if('blik' === target && checkBylaw && checkPersonalData) {
                $('form[form-target="' + target + '"] input[type="submit"]').show();
                result = true;
            } else if('dotpay' === target && checkBylaw && checkPersonalData) {
                $('form[form-target="' + target + '"] input[type="submit"]').show();
                result = true;
            }
            
            return result;
        }
        
        function runBlockUI() {
            $.blockUI({
                message: "<?php echo $data['message'] ?>",
                baseZ: 99999,
                overlayCSS: {
                    background: "#fff",
                    opacity: 0.6
                },
                css: {
                    padding: "20px",
                    zindex: "9999999",
                    textAlign: "center",
                    color: "#555",
                    border: "3px solid #aaa",
                    backgroundColor: "#fff",
                    cursor: "wait",
                    lineHeight: "24px"
                }
            });
        }
    });
<?php endif; ?>
